import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import { AuthHeader } from "./AuthHeader";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { StoreUserInDatabase } from "./StoreUserInDatabase";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/sign-in">
      <html
        lang="en"
        className={`${roboto.variable} ${robotoMono.variable}`}
      >
        <body className={`${roboto.className} antialiased`}>
          <AuthHeader />
          <ConvexClientProvider>
            <StoreUserInDatabase />
            {children}
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
